### ISSUE TITLE
Derive "region" variable from the address

### ISSUE THREAD

**Issue by jwestw** [ThomasHSimm/Pesticide#16]
The adress data is too unique and not useful for ML, but aggregated up to region, it might be. Therefore it would be best to create a derived variable column, `region`. 

Addresses can be categorised as "NE" "NW" "SE" etc, which can later be one-hot-encoded.

**Comment by ThomasHSimm** [comment]
Doing as per https://thomashsimm.github.io/PesticideDocs/UK_areas.html

**Comment by ThomasHSimm** [comment]
That link is really good! Seems like I looked at everything but that one

The way I'm doing at the moment is 
- have a csv with all postcodes and a column for the region. 
- Convert this to a dict and use pd.map/replace on the actual data's postcodes to get the area for every postcode. 
 
Seems to work ok even if though file is big but may need some check if fails to match
